Allow default values
vinted/interactor-initializer pull request #9
Opened 2018-04-06 08:57 UTC by ramunas-peleckas

It is often useful to initialize an interactor with defaults values. This PR enables that. For example `initialize_with`can now be used like this: `initialize_with :user, errors: []`

@vinted/backend

2018-04-06 09:29 UTC, raimondasv commented on lib/interactor/initializer/initialize.rb
> +    default_params = defaults.keys.map { |key| "#{key}: #{defaults[key]}" }
this will brake for `nil`

2018-04-06 09:30 UTC, raimondasv commented on lib/interactor/initializer/initialize.rb
> +    default_params = defaults.keys.map { |key| "#{key}: #{defaults[key]}" }
And for BigDecimal

2018-04-06 09:31 UTC, raimondasv commented
You are relying on string representation of the type. Which is not that resilient.

2018-04-06 09:32 UTC, raimondasv commented on lib/interactor/initializer/initialize.rb
> +    default_params = defaults.keys.map { |key| "#{key}: #{defaults[key]}" }
And for Hash.new(0)

2018-04-06 09:34 UTC, raimondasv commented on lib/interactor/initializer/initialize.rb
> +    default_params = defaults.keys.map { |key| "#{key}: #{defaults[key]}" }
And for any other object with Class.new

2018-04-06 09:37 UTC, raimondasv commented
This change implies you can do
```ruby
initialize_with user: current_user
``` 
which you cannot

2018-04-06 09:38 UTC, raimondasv requested changes
Discussion is required

2018-04-17 07:36 UTC, ramunas-peleckas commented
If we want to support default values AND type signature there is no elegant way of doing this (at least none that I'm aware of). If default values were used directly to construct the signature the resulting initialize method would look something like this `def initialize(user = #<User:0x007fb4e00bc060>)` (since the signature is constructed by evaluating a string) and it wouldn't work. In order to make this work the hack is used and the signature is constructed with `nil` as a default value, like this: `def initialize(user = nil)`. The proper default values are then assigned in a separate method.

Pros:
- default values are now supported

Cons:
- Somewhat hacky approach
- `initialize_defaults` method is defined which might cause some unexpected behaviour if overriden.

I would like to know your opinions

@vinted/backend

2018-04-17 07:54 UTC, raimondasv approved these changes

2018-04-17 07:56 UTC, justaskz commented
@ramunas-peleckas could you please update documentation

2018-04-17 07:58 UTC, tomasv commented
> `initialize_with :user, errors: []`

Isn't this dangerous? All instances will get the same array instance as their default value.

2018-04-17 07:59 UTC, OlegSmelov commented on lib/interactor/initializer/initialize.rb
> +          instance_variable_set("@#{name}", defaults[name]) unless instance_variable_get("@#{name}")
So if you call the interactor with `.for(value: nil)` it would fall back to the default? Doesn't seem right.

2018-04-17 08:06 UTC, OlegSmelov commented
If I understand correctly, the defaults (the objects) are now shared among all calls. Which means that if they are mutated, the mutated values will be kept. This is different to when you have default values in method's definition (`def f(x: Object.new)` - Object is instantiated each time it is called). This is probably okay if we are aware of this and never mutate any of parameters.

2018-04-17 08:09 UTC, OlegSmelov commented
Is there a reason we can't use one method call for initialization? E.g. `initialize_with :value, value_with_default: 'test'`. It would then set defaults to a hash, create initializer without the defaults, set the defaults where necessary.

2018-04-17 08:10 UTC, OlegSmelov commented
> Isn't this dangerous? All instances will get the same array instance as their default value.

Sounds like we should enforce frozen defaults.

2018-04-17 10:44 UTC, ramunas-peleckas commented
Alright. I feel like freezing the defaults as well as `.for(value: nil)` not working as expected brings additional complexity/confusion and therefore not worth the effort. Closing.

2018-04-17 10:44 UTC, closed without merging